### ISSUE TITLE
[Bounty] [wallet-cli] create wallet - error when creating a wallet - password are numbers

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#100]
BugReport
------------
i try to create an wallet with the command RegisterWallet
![image](https://user-images.githubusercontent.com/39301026/41083225-eb8e2ef0-6a30-11e8-9b2d-d83995e5354c.png)
I enter the following password: 1234567890987654321234567890

i get the following error message:
![image](https://user-images.githubusercontent.com/39301026/41083081-9b9ac84a-6a30-11e8-89c1-bcc67fe78955.png)

Debug:
![image](https://user-images.githubusercontent.com/39301026/41083348-490585ba-6a31-11e8-8658-5ed8b0afa204.png)
the problem exists only if i give a password which contains only numbers

test with letters and numbers, it works:
![image](https://user-images.githubusercontent.com/39301026/41083423-767868be-6a31-11e8-9456-954a1a9b1620.png)

![image](https://user-images.githubusercontent.com/39301026/41083440-7f3a71b8-6a31-11e8-8581-7af926593e82.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
06. June 2018 8:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by PMD3VSolution** [comment]
I can reproduce the error.

**Comment by zergweak** [comment]
1234567890987654321234567890 is weak password.  We add tips for it. Thank you very much.
