### ISSUE TITLE
[Bounty] [wallet-cli][Security] create wallet - password with spaces - space separates password - no check

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#101]
Bug Report
-------
if i enter a password with spaces, the length of the characters to space is important. the algorytmus only checks the minimum number of characters but does not search the password for spaces. so the entered password does not match the one the keyfile is encrypted with.
That's a security risk from my point of view.

example: i enter the following password :
^[[11~^[[12~^[[13~^[[14~^[[15~^[[17~^[[18~^[[19~   ^[[20~^[[21~^[[23~^[[24~askju3892u32o^12190127("!="!/!"(&§!=$"!!R"T"E/"!E(*'*QÄDAÜSD

description
------------
![image](https://user-images.githubusercontent.com/39301026/41084449-8716a282-6a34-11e8-8503-138990233482.png)

Evidence/Test
--------------
i create a wallet with the password described above
![image](https://user-images.githubusercontent.com/39301026/41084248-d9afb3b8-6a33-11e8-8622-a5178c3d31d2.png)
the user does not get an error message and assumes that the password he entered is also the password with which the file is encrypted. but unfortunately this is not correct

now i log in with the first part of the password:
![image](https://user-images.githubusercontent.com/39301026/41084649-1071b7ce-6a35-11e8-8c8e-3099cc39bc31.png)

![image](https://user-images.githubusercontent.com/39301026/41084733-3e5b1482-6a35-11e8-9a49-a00d10b18a25.png)

i choose my file:
![image](https://user-images.githubusercontent.com/39301026/41084784-5a23cc72-6a35-11e8-887f-620f0fa411d4.png)

login success
![image](https://user-images.githubusercontent.com/39301026/41084829-79343584-6a35-11e8-889b-54164c665be3.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
07. June 2018 10:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by PMD3VSolution** [comment]
![image](https://user-images.githubusercontent.com/39301026/41087738-b1fba8ae-6a3d-11e8-8182-b75777511a06.png)

**Comment by zergweak** [comment]
I will fix it , thank you very much.
