### ISSUE TITLE
[Bounty] [wallet-cli] - Send coin - parameter definition - different amount - transaction error

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#102]
Bug Report
----------
to send the TRX I enter the following command:
![image](https://user-images.githubusercontent.com/39301026/41085981-dec8b12e-6a38-11e8-99a2-84f5cbcddfad.png)
Command:
sendcoin -Tron-Address- -number of trx-
![image](https://user-images.githubusercontent.com/39301026/41086024-0938a9be-6a39-11e8-81c5-caf6b178574a.png)

summary
---------

![image](https://user-images.githubusercontent.com/39301026/41086359-1c79325e-6a3a-11e8-8c87-3c509dfa0f0f.png)

i confirm the transaction and enter my password:
![image](https://user-images.githubusercontent.com/39301026/41086256-b8042554-6a39-11e8-9e2f-a7d3a0e28d9b.png)

confirmation
-------------
![image](https://user-images.githubusercontent.com/39301026/41086269-c3ec57b0-6a39-11e8-9fa8-d56c803d7dbe.png)
![image](https://user-images.githubusercontent.com/39301026/41086385-3757c1b2-6a3a-11e8-9414-9cb4e1f9ce9f.png)

but when I check my target wallet I see something else:
![image](https://user-images.githubusercontent.com/39301026/41086480-7722954c-6a3a-11e8-8118-d42d2ee46ebb.png)

details
--------
![image](https://user-images.githubusercontent.com/39301026/41086538-990d43dc-6a3a-11e8-8851-2a6cd37e89e6.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
07. June 2018 10:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by PMD3VSolution** [comment]
I was able to reproduce the error several times.

**Comment by PMD3VSolution** [comment]
the number of my trx will be subtracted correctly:

![image](https://user-images.githubusercontent.com/39301026/41087075-04234a58-6a3c-11e8-9718-6cc3bb6dea47.png)

**Comment by zergweak** [comment]
Amount is drops in wallet-cli , do not trx. Thank you anyway
