### ISSUE TITLE
[Bounty] [wallet-cli][documentation issue] - How to freeze/unfreeze balance

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#103]
doc Bug
----------
based on the documentation, the freeze balance command is "freezebalance password amount time".
![image](https://user-images.githubusercontent.com/39301026/41087889-400e1488-6a3e-11e8-9181-414c0108b336.png)

but it looks different in real life:
![image](https://user-images.githubusercontent.com/39301026/41087954-77850a98-6a3e-11e8-82df-b2deff290706.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
07. June 2018 10:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by zergweak** [comment]
You should follow the instructions in the code.
frozen_balance need greater than or equal to 1000000 (drops) and frozen_duration should be equal to 3(days)
