### ISSUE TITLE
Wallet build issue

### ISSUE THREAD

**Issue by bharathimnw** [tronprotocol/wallet-cli#104]
Cannot build wallet. 
D:\gitron\wallet-cli>gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'wallet'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
     Required by:
         project :
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not get resource 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
            > Could not HEAD 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve gradle.plugin.com.liferay:gradle-plugins-node:4.3.0.
     Required by:
         project :
      > Could not resolve gradle.plugin.com.liferay:gradle-plugins-node:4.3.0.
         > Could not get resource 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/gradle/plugin/com/liferay/gradle-plugins-node/4.3.0/gradle-plugins-node-4.3.0.pom'.
            > Could not GET 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/gradle/plugin/com/liferay/gradle-plugins-node/4.3.0/gradle-plugins-node-4.3.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 6s

D:\gitron\wallet-cli>gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'wallet'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
     Required by:
         project :
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not get resource 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
            > Could not HEAD 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve gradle.plugin.com.liferay:gradle-plugins-node:4.3.0.
     Required by:
         project :
      > Could not resolve gradle.plugin.com.liferay:gradle-plugins-node:4.3.0.
         > Could not get resource 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/gradle/plugin/com/liferay/gradle-plugins-node/4.3.0/gradle-plugins-node-4.3.0.pom'.
            > Could not GET 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/gradle/plugin/com/liferay/gradle-plugins-node/4.3.0/gradle-plugins-node-4.3.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 3s

D:\gitron\wallet-cli>

**Comment by kookiekrak** [comment]
Hi @bharathimnw,

What version of java and what OS are you on? Additionally, are you on our developer slack? email me at tian@tron.network for an invite :)

**Comment by bharathimnw** [comment]
Hi @kookiekrak 
I use windows 10 OS and java version "1.8.0_121"

**Comment by SnearK6354** [comment]
I'm also having difficulties to build wallet-cli. Can you please check ?

[logfortron.txt](https://github.com/tronprotocol/wallet-cli/files/2084606/logfortron.txt)

**Comment by zergweak** [comment]
@SnearK6354  Try again, may be fixed it now.

**Comment by indocolabs** [comment]
i have same issue, can u help me?
