### ISSUE TITLE
Impossible to registerwallet

### ISSUE THREAD

**Issue by SnearK6354** [tronprotocol/wallet-cli#111]
Hi,

The password necessary to registerwallet must be

At least 8 characters
Contain uppercase, lowercase, numeric and other (define other)
not contain 3 duplicate numbers or letters
not contain 3 consecutive number or letter
not a weak and easy to guess password combinatio

"Wh@tTheBing_isT315" should be acceptable... 

No matter how hard I try... i am never able to use the registerwallet function.

Can you please provide me an acceptable password to test?

![wallet-cli](https://user-images.githubusercontent.com/35176703/41223835-2f308378-6d6b-11e8-84d8-bc6e9f761390.jpg)

Thanks a lot.

**Comment by zergweak** [comment]
I just tried it, Wh@tTheBing_isT315 is valid password.
You can also try 1q2w#E$R.

**Comment by SnearK6354** [comment]
Dear Zergweak, 

I just tried again : removed wallet-cli folder. Redownloaded from github, rebuild, then I tried:

registerwallet 1q2w#E$R

==> password is too weak
