### ISSUE TITLE
[BOUNTY]Liar - About Tron and Justin Sun

### ISSUE THREAD

**Issue by tronisliar** [tronprotocol/wallet-cli#114]
This is a hoax designed to defraud the whole community and develop wallet without compensation.
A large number of developers have been used and paid a lot of energy, but they can not get any returns.
Claiming $200 million worth of field loans, but with a maximum of $700 thousand in fact. You wait to see it.

No bounty for any bug

**Comment by frontr-uk** [comment]
kookiekrak,
People will talk bad as that's there life mission. He had the time to create an account and publish this Sh**. That's his life mission. Let's  leave these type people alone as you dont want to get your hands dirty :)

One the other side note, keep the good stuff going and congrats on doing a good job even after what people say. Publicity is publicity in the end :)
