### ISSUE TITLE
[Bounty] [wallet-cli][Security] create wallet - password contains tab stop - no check

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#131]
Bug Report
------------
when entering the password with a tabstop... the password is separated. the program does not check if the passwords are the same

example: i enter the following password :
Please input password.
<===========--> 85<===========--> 85<===========<=======<===========<===========<===========--> 85% EXECUTING [8m 59s]
> :run
^[[11~^[[12~^[[13~^[[14~^[[15~^[[17~^[[18~^[[19~        ^[[20~^[[21~^[[23~^[[24~

I will then be asked to enter the password again:

Please input password again.
<==<===========--> 85<===========--> 85<===========--> 8<===========<===========<===========--> 85% EXECUTING [12m 39s]
> :run
   ^[[11~^[[12~^[[13~^[[14~^[[15~^[[17~^[[18~^[[19~     ^[[24~^[[23~^[[21~^[[20~

<==<===========--> 85<===========--> 85<===========--> 8<===========<===========<===========--> 85% EXECUTING [12m 41s]
03:58:05.621 INFO  [main] [TestClient](TestClient.java:110) Register a wallet successful, keystore file name is UTC--2018-06-19T07-58-05.621000000Z--TAaBPUdkGXfL2AVTiLyVAJ1zGe5rqLwqqH.json
<===========--> 85% EXECUTING [13m 13s]

-> !the wallet was successfully created!

password:
^[[11~^[[12~^[[13~^[[14~^[[15~^[[17~^[[18~^[[19~        ^[[20~^[[21~^[[23~^[[24~

confirm password
 ^[[11~^[[12~^[[13~^[[14~^[[15~^[[17~^[[18~^[[19~     ^[[24~^[[23~^[[21~^[[20~

fault:
but the entered password and the confirm password do not match!!!

![grafik](https://user-images.githubusercontent.com/39301026/41584613-120e1d3a-73a8-11e8-990d-c09a5187b8a1.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
19. June 2018 10:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by zergweak** [comment]
Many systems is allowed password contain space and TAB

**Comment by PMD3VSolution** [comment]
yes that's right, but not the cli wallet!!! it separates the password when using a should character
