### ISSUE TITLE
[Bounty] [wallet-cli][Security] Register wallet - Wallet password too complex, password is not accepted 

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#139]
Bug Report
-------------
i have generated a secure password for my wallet.

my password:
qnSk4J_Pu>9H§zTt90Z(@5§_C)z!F.D3>BÖhöS&y!rhf)k>Wu@{~$pj@~GqQd8

it is complies with password rules:
The password should be at least 8 characters.
The password should contains uppercase, lowercase, numeric and other.
The password should not contain more than 3 duplicate numbers or letters; For example: 1111.
The password should not contain more than 3 consecutive Numbers or letters; For example: 1234.
The password should not contain weak password combination; For example:
ababab, abcabc, password, passw0rd, p@ssw0rd, admin1234, etc.

if i want to create the wallet with the password i get the following error message:
enter the register Wallet command :
![grafik](https://user-images.githubusercontent.com/39301026/41732294-f7f75364-7580-11e8-8ee1-732bb694205e.png)

i enter the password:
![grafik](https://user-images.githubusercontent.com/39301026/41732368-24a7086e-7581-11e8-96d7-cea9e7be1415.png)

i get this error message:
![grafik](https://user-images.githubusercontent.com/39301026/41732398-39f275b4-7581-11e8-9a24-6986cf569c92.png)

but the password is not too short!

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
19. June 2018 10:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by zergweak** [comment]
For security, the password should not be too simple.

**Comment by PMD3VSolution** [comment]
this password is simple?
qnSk4J_Pu>9H§zTt90Z(@5§_C)z!F.D3>BÖhöS&y!rhf)k>Wu@{~$pj@~GqQd8
