### ISSUE TITLE
Sync wallet-cli with wallet on Tronscan

### ISSUE THREAD

**Issue by lamductan** [tronprotocol/wallet-cli#142]
How can I sync wallet-cli wallet with my wallet on tronscan? I try to add my private key to local witnesses in config.conf and rebuild java-tron but it still not sync. I use my account on https://test.tronscan.org. If I follow [this instruction](https://github.com/fbsobreira/tron-testnet-config), I can sync wallet-cli with my account on http://35.193.47.70:3000/#/

**Comment by lamductan** [comment]
You must use API ImportWallet.

**Comment by zk19862018** [comment]
+
