### ISSUE TITLE
Address Altered when calling GetAccount

### ISSUE THREAD

**Issue by justforfun0706** [tronprotocol/wallet-cli#153]
![1](https://user-images.githubusercontent.com/40877886/42358149-bde5d72a-810d-11e8-9713-8101376358dd.png)
![2](https://user-images.githubusercontent.com/40877886/42358150-be5fc968-810d-11e8-864e-e46186f43660.png)

As shown in the pic1, I revoked GetAccount with the designated addresses.
However in pic2 of the returned result, the address, specifically, the top 4 characters of original address "TMeW" was altered to "3QJmnh".  
Why is this happending? 
Is it intended or  just a bug?

**Comment by lamductan** [comment]
Have you tried to getBlock? Does wallet-cli provide your desirable result? The problem seems like that you are not connected to any fullnode or in wallet-cli config.conf you uncomment soliditynode part but you don't connect to any soliditynode.

**Comment by LingTian** [comment]
Hello,
you should change the full node & solidity node setting in configure file.

Full Node
GRPC port: 50051
P2P network port: 18888
HTTP port : 8090
54.236.37.243
52.53.189.99
18.196.99.16
34.253.187.192
52.56.56.149
35.180.51.163
54.252.224.209
18.228.15.36
52.15.93.92
34.220.77.106
13.127.47.162
13.124.62.58
47.74.149.206
35.182.37.246
47.90.215.84
47.254.77.146
47.74.242.55
47.75.249.119
47.90.201.118
34.250.140.143
35.176.192.130
52.47.197.188
52.62.210.100
13.231.4.243
47.254.27.69
35.154.90.144
13.125.210.234
47.88.174.175
47.75.249.4
Solidity Node
GRPC port: 50051
HTTP port : 8091
47.89.187.247
47.91.18.255
47.75.10.71
47.251.52.228
47.251.48.82
47.74.147.80
34.234.164.105
18.221.34.0
35.178.11.0
35.180.18.107

check this:
https://github.com/tronprotocol/Documentation/blob/master/TRX_CN/Official_Public_Node.md
