### ISSUE TITLE
Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetAccount

### ISSUE THREAD

**Issue by qings2329** [tronprotocol/wallet-cli#169]
my config :

net {
 type = mainnet
}

fullnode = {
  ip.list = [
    "192.168.112.66:50051"
  ]
}

soliditynode = {
  ip.list = [
    "192.168.112.66:50051"
  ]
}

my code :

            client.login(password.toCharArray());
            Protocol.Account account = client.queryAccount();

 run and get exception :

io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetAccount
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
	at org.tron.api.WalletSolidityGrpc$WalletSolidityBlockingStub.getAccount(WalletSolidityGrpc.java:596)

Anybody know how to handle this problem ?

**Comment by LingTian** [comment]
Hello,
you should change the full node & solidity node setting in configure file.

Full Node
GRPC port: 50051
P2P network port: 18888
HTTP port : 8090
54.236.37.243
52.53.189.99
18.196.99.16
34.253.187.192
52.56.56.149
35.180.51.163
54.252.224.209
18.228.15.36
52.15.93.92
34.220.77.106
13.127.47.162
13.124.62.58
47.74.149.206
35.182.37.246
47.90.215.84
47.254.77.146
47.74.242.55
47.75.249.119
47.90.201.118
34.250.140.143
35.176.192.130
52.47.197.188
52.62.210.100
13.231.4.243
47.254.27.69
35.154.90.144
13.125.210.234
47.88.174.175
47.75.249.4
Solidity Node
GRPC port: 50051
HTTP port : 8091
47.89.187.247
47.91.18.255
47.75.10.71
47.251.52.228
47.251.48.82
47.74.147.80
34.234.164.105
18.221.34.0
35.178.11.0
35.180.18.107

check this:
https://github.com/tronprotocol/Documentation/blob/master/TRX_CN/Official_Public_Node.md
