### ISSUE TITLE
Wallet-Cli and tronscan.org adress are showing different each other Why?

### ISSUE THREAD

**Issue by issevpar** [tronprotocol/wallet-cli#204]
When i register a wallet in wallet-cli it is ok.Generating successful and generation an adress.
![konsol](https://user-images.githubusercontent.com/85240/44100297-73266610-9fed-11e8-919e-f7923d91529e.png)
But when i login my private key in tronscan.org login is successful but account adress is different. Why?Which one of them may i use? I am confused.
![tronscanadress](https://user-images.githubusercontent.com/85240/44100425-c0f9d138-9fed-11e8-9b9a-85878409d315.png)

**Comment by aaaking** [comment]
config ./src/main/resources/config.conf, the address will be different if you set type = testnet, so, you should set type = mainnet. It is ip.list to determine it is testnet or mainnet

**Comment by issevpar** [comment]
Yes i have checked already the conf.file and rebuild gradlew before writing here.in my conf file set mainnet. I can login tronscan using this json file. I dont understand why.
