### ISSUE TITLE
How can I get the test TRX

### ISSUE THREAD

**Issue by CooperLee123** [tronprotocol/wallet-cli#217]
Hello,  I have the wallet on the testnet and then I want to get test TRX, How can I get

**Comment by haidt18** [comment]
@CooperLee123  have you got test trx?

**Comment by CooperLee123** [comment]
Hi, I. Meet a new trouble ness, the soliditynode is still at height 256000,not to sync, but last remote node is 3500000

**Comment by haidt18** [comment]
@CooperLee123 try this bro 
const fullNode = new HttpProvider('http://13.125.210.234:8090');
const solidityNode = new HttpProvider('http://39.105.66.80:8091');
const eventServer = 'https://api.trongrid.io/';

**Comment by zk19862018** [comment]
http://testnet.tronex.io/join/getJoinPage
