### ISSUE TITLE
what is to insert here and where?

### ISSUE THREAD

**Issue by TRON-FAN** [tronprotocol/wallet-cli#230]
![image](https://user-images.githubusercontent.com/42068552/46771919-e5d81e80-ccf5-11e8-94c4-db8e68d6223e.png)

**Comment by tmao1129** [comment]
@TRON-FAN  It depends on which ip addresses you already have your Full Node and Solidity Node configured to. For example, if you had gone through the docker quickstart (https://developers.tron.network/docs/getting-started-1), then your Full Node would be configured to 127.0.0.1:8090 for HTTP and 127.0.0.1:50051 for gRPC. In that case, replace "fullnode ip : port" in this config file with "127.0.0.1:50051"). Solidity node is optional. I believe Wallet-CLI only interacts through the gRPC port. This change will allow your wallet to communicate to the node you have setup. 

Also, please join our TRON Developers Discord channel at https://discord.gg/GsRgsTD. Here we have many developers and Tron engineers discussing technical issues, such as questions like yours. Thanks!

**Comment by jonnyhsy** [comment]
@tmao1129  how to get testnet's ip lists? Thanks!

**Comment by LingTian** [comment]
Hello,
you can change the full node & solidity node setting in configure file. 
Hope it helps XD

Full Node
GRPC port: 50051
P2P network port: 18888
HTTP port : 8090
54.236.37.243
52.53.189.99
18.196.99.16
34.253.187.192
52.56.56.149
35.180.51.163
54.252.224.209
18.228.15.36
52.15.93.92
34.220.77.106
13.127.47.162
13.124.62.58
47.74.149.206
35.182.37.246
47.90.215.84
47.254.77.146
47.74.242.55
47.75.249.119
47.90.201.118
34.250.140.143
35.176.192.130
52.47.197.188
52.62.210.100
13.231.4.243
47.254.27.69
35.154.90.144
13.125.210.234
47.88.174.175
47.75.249.4
Solidity Node
GRPC port: 50051
HTTP port : 8091
47.89.187.247
47.91.18.255
47.75.10.71
47.251.52.228
47.251.48.82
47.74.147.80
34.234.164.105
18.221.34.0
35.178.11.0
35.180.18.107

check this:
https://github.com/tronprotocol/Documentation/blob/master/TRX_CN/Official_Public_Node.md
