### ISSUE TITLE
getTransactionById && getTransactionInfoById

### ISSUE THREAD

**Issue by testrain** [tronprotocol/wallet-cli#254]
1 .What's the difference? 
2. Shouldn't 'id' be renamed to 'hash', right?
3. each command should have example usage and documentations. e.g. deploycontract's behavior actually differs from what [doc](https://developers.tron.network/docs/setup-dapp-environment#section-4-deploy-smart-contract-via-wallet-cli) says

**Comment by LingTian** [comment]
Actually I have some experience in Tron.
1. getTransactionInfoById is useful, it will show your energy cost per transaction.
2. getaccountnet is useful when you want to check your bandwidth and getaccountresource is used for energy
3.the documentation is not latest one, sometimes you need to try and use help in commandline.
Hope it helps little bit

**Comment by jonnyhsy** [comment]
Thank you Tian

**Comment by zk19862018** [comment]
getTransactionInfoById returns:
{
    "id": "0ac618919fc2f2452606e7ad41c242334b548589449583e57f01fd80a020229b",
    "fee": 3650,
    "blockNumber": 11000014,
    "blockTimeStamp": 1569763622000,
    "contractResult": [
        ""
    ],
    "receipt": {
        "net_fee": 3650
    }
}


getTransactionById returns:
{
    "ret": [
        {
            "contractRet": "SUCCESS"
        }
    ],
    "signature": [...],
    "txID": "0ac618919fc2f2382606e12341c242334b548589456583e57f01fd80a020229b",
    "raw_data": {
        "data": "...",
        "contract": [
            {
                "parameter": {
                    "value": {
                        "amount": 1,
                        "asset_name": "...",
                        "owner_address": "...",
                        "to_address": "..."
                    },
                    "type_url": "type.googleapis.com/protocol.TransferAssetContract"
                },
                "type": "TransferAssetContract"
            }
        ],
        "ref_block_bytes": "1137",
        "ref_block_hash": "cc717526494ae81c",
        "expiration": 1568863853000
    },
    "raw_data_hex": "..."
}

they focus on different data
