### ISSUE TITLE
The latest example of freezeBalance

### ISSUE THREAD

**Issue by LingTian** [tronprotocol/wallet-cli#255]
Hello, there are lots of developers ask me about freezeBalance quesiton.
The example in the readme is not latest one.
You can try to freeze your tron for energy/bandwidth with following command.

freezeBalance 100000000 3 1 address
freezeBalance amount days energy/bandwidth address

**Comment by LingTian** [comment]
Hope this will help~

**Comment by zk19862018** [comment]
Thank you for ur issue. The latest documentation is at https://tronprotocol.github.io/documentation-EN/clients/wallet-cli/
