### ISSUE TITLE
Desktop wallet for Win10 with voting functionality support

### ISSUE THREAD

**Issue by travek** [tronprotocol/wallet-cli#264]
Hi!

I was using Tron Desktop Wallet but the tram announced that this wallet is deprecated.
Please what wallet I can use to have a voting functionality operating and considering this to be a desktop wallet.

Thanks

**Comment by zk19862018** [comment]
you can use wallet-cli.
https://tronprotocol.github.io/documentation-EN/clients/wallet-cli/
