### ISSUE TITLE
A question about wallet password

### ISSUE THREAD

**Issue by travek** [tronprotocol/wallet-cli#265]
Hi!
I want to start using wallet-cli.
I already have an account\wallet in TRON network and I have private key of a account.
How I can freeze/unfreeze and vote using a private key?
I can't understand how I can get a password for command-cli commands from private key of already existing account ?

**Comment by zk19862018** [comment]
Please refer to: https://tronprotocol.github.io/documentation-EN/clients/wallet-cli/
