### ISSUE TITLE
//set genesis.block.assets address to yours. restart java-tron. getbalance

### ISSUE THREAD

**Issue by cdragon2018** [tronprotocol/wallet-cli#28]
Dear Admin,

I am a beginner of Java program. I tried google it but couldn't find any answers. Could you provide a detailed command line of how to preform 
//set genesis.block.assets address to yours. 
restart java-tron.
 getbalance

Thanks a lot for the help
Regards
cdragon

**Comment by netoescripol** [comment]
I have the same problem

**Comment by Cyphernode** [comment]
I have done the genesis settings step  it doesn't work and might be a bug because after you run your node the network has to sync in order to update your local wallet balance.

**Comment by cdragon2018** [comment]
Don’t know why tron team provide broken command lines in the wallet-cli wiki? Should have tested all the command lines before release to the public

**Comment by bondibox** [comment]
@Cyphernode the way these jar apps seem to work is at runtime it recompiles and rewrites the config.conf in the build/ tree, using the config.conf file in the src/ tree. And changes you make to the former will be lost, changes made to the latter will be mirrored to the former at runtime.

**Comment by SnearK6354** [comment]
I use tron.network website to generate Address + password + PK
==> OK


then I import the wallet through wallet-cli ==> result is OK
_15:57:12.552 [main] INFO TestClient - Import a wallet and store it successful !!_


I request Test TRX on tron.network
==> Test TRX appears in my balance (+10 000)

However, my balance remains always 0 under wallet-cli.

Can you please explain how to synchronize ?
Is it necessary to modify the conf file under wallet-cli to manage the synchronization?
If so, can you please clarify how to proceed?


I made an additional test:

I modified PWD through wallet-cli
_Login pwd
Changepassword oldpwd newpwd_
This modification is well applied under wallet-cli

But on tronnetwork, I still need to use the oldpwd.

**The main blocking point is : how to synchronize the two?**

Thanks a lot for your help.

**Comment by bondibox** [comment]
@SnearK6354 that is the crux of the issue. Whether I'm running the blockchain explorer from wallet-cli or wallet-web it never shows the rest of the chain. No blocks and no nodes.

**Comment by bondibox** [comment]
Also I should add that the proper place for the config file is 1 level up in the build directory but when I was trying to enter my private key it would throw an exception & handle it same as if I was modifying the src file but after I corrected the syntax it created a completely different set of errors. Not at my desk so I can't replicate it, but it was as if it was trying to create an object from outside the class.

**Comment by Cyphernode** [comment]
@bondibox  noted thanks for the info!
