### ISSUE TITLE
[QUESTION] Is there alternative software like wallet-cli but with JSON-RPC support?

### ISSUE THREAD

**Issue by gituser** [tronprotocol/wallet-cli#290]
Hi.

I'd like to know if there is a software which offers wallet-cli functionality but with JSON-RPC support.

Is there any software which allows you to query tron blockchain without running full TRON node?

NOTE: I need local version to sign transactions/create accounts locally and just broadcast data into blockchain or query blockchain for certain transaction history.

Thanks.

**Comment by zk19862018** [comment]
you can use:

https://github.com/tronscan
https://github.com/TRON-US/tronweb
