### ISSUE TITLE
[Question] how to calculate the number of bytes of transactions

### ISSUE THREAD

**Issue by gologo13** [tronprotocol/wallet-cli#292]
Hi, guys. I have a question how to calculate the number of bytes of transactions in order to calculate the exact fee size under exhausted bandwidth condition.

> Consume the transaction initiator's TRX, calculated as the number of bytes in the transaction * 10 SUN.
> https://developers.tron.network/docs/bandwith#section-normal-transaction

I know how to calculate it theoretically, so wrote the following code to test, but I found the actual fee size was different from bytes of transaction * 10.

```java
GrpcClient grpcClient = new GrpcClient(cfg.getRpcHost() + ":" + cfg.getRpcPort(), null);
Protocol.TransactionInfo txInfo = grpcClient.getTransactionInfoById(hash).get(); // let say we have a tx hash

System.out.println("tx-size * 10 = " + grpcClient.getTransactionById(txId).get().getSerializedSize() * 10);
System.out.println("NetUsage = " + txInfo.getFee());

// Result
tx-size * 10 = 2080
NetUsage = 2680
```

Am I miss something? Could you tell me how can I calculate the exact fee size?
Thanks in advance.

**Comment by zk19862018** [comment]
Hi, by calling "grpcClient.getTransactionById(txId).get().getSerializedSize()", the result is the transaction size without execution result. 
We add a 60 bytes execution result into the transaction. 
So, the correct way to calculate is:
System.out.println("tx-size * 10 = " + (grpcClient.getTransactionById(txId).get().getSerializedSize()+60) * 10);

**Comment by gologo13** [comment]
@zk19862018 thank you for the reply! I'll give it a shot.

**Comment by zk19862018** [comment]
+

**Comment by JessDotJS** [comment]
Hello, is there a way of achieving this with TronWeb?

**Comment by matilareo** [comment]
Need to achive this with tron-web, is there any method ??

**Comment by heyvipho** [comment]
@JessDotJS @matilareo Hello, I found the solution in JavaScript. If you check [proto file](https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto) you will see what does Transaction consist of.

```protobuf
message Transaction {

  // ...

  raw raw_data = 1;
  // only support size = 1,  repeated list here for muti-sig extension
  repeated bytes signature = 2;
  repeated Result ret = 5;
}
```

So if we plus raw_data byte length, signature(s) byte length and extra fixed 69 bytes we will get transaction byte length and bandwidth. I'm not sure it's correct way, but I checked some transactions and values was equal.

Code works in Node.js. There isn't Buffer In browser, so it's necessary to use another way to get byte length

```javascript
const tronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io',
})
const transactionID = 'f23c438a1675cd0a93a8cd07145a97aad8b52e704b05749df72ec9b7730541bc'
tronWeb.trx.getConfirmedTransaction(transactionID).then(({raw_data_hex, signature}: any) => {
    console.log('raw_data_hex:', raw_data_hex)
    console.log('signature:', signature[0])
    const transactionByteLength = 9 + 60 + Buffer.from(raw_data_hex, 'hex').byteLength + Buffer.from(signature[0], 'hex').byteLength
    console.log('transaction byte length:', transactionByteLength)
})
```

**Comment by minseon9** [comment]
> @JessDotJS @matilareo Hello, I found the solution in JavaScript. If you check [proto file](https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto) you will see what Transaction consists of.
> 
> ```proto
> message Transaction {
> 
>   // ...
> 
>   raw raw_data = 1;
>   // only support size = 1,  repeated list here for muti-sig extension
>   repeated bytes signature = 2;
>   repeated Result ret = 5;
> }
> ```
> 
> So if we plus raw_data byte length, signature(s) byte length and extra fixed 69 bytes, we will get transaction byte length and bandwidth. I'm not sure if it's correct way, but I've checked some transactions and values were equal.
> 
> Code works in Node.js. There isn't Buffer In browser, so it's necessary to use another way to get byte length
> 
> ```js
> const tronWeb = new TronWeb({
>     fullHost: 'https://api.trongrid.io',
> })
> const transactionID = 'f23c438a1675cd0a93a8cd07145a97aad8b52e704b05749df72ec9b7730541bc'
> tronWeb.trx.getConfirmedTransaction(transactionID).then(({raw_data_hex, signature}) => {
>     console.log('raw_data_hex:', raw_data_hex)
>     console.log('signature:', signature[0])
>     const transactionByteLength = 9 + 60 + Buffer.from(raw_data_hex, 'hex').byteLength + Buffer.from(signature[0], 'hex').byteLength
>     console.log('transaction byte length:', transactionByteLength)
> })
> ```

Could you explain where that fixed 69 bytes come from?

**Comment by heyvipho** [comment]
> > @JessDotJS @matilareo Hello, I found the solution in JavaScript. If you check [proto file](https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto) you will see what Transaction consists of.
> > ```proto
> > message Transaction {
> > 
> >   // ...
> > 
> >   raw raw_data = 1;
> >   // only support size = 1,  repeated list here for muti-sig extension
> >   repeated bytes signature = 2;
> >   repeated Result ret = 5;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So if we plus raw_data byte length, signature(s) byte length and extra fixed 69 bytes, we will get transaction byte length and bandwidth. I'm not sure if it's correct way, but I've checked some transactions and values were equal.
> > Code works in Node.js. There isn't Buffer In browser, so it's necessary to use another way to get byte length
> > ```js
> > const tronWeb = new TronWeb({
> >     fullHost: 'https://api.trongrid.io',
> > })
> > const transactionID = 'f23c438a1675cd0a93a8cd07145a97aad8b52e704b05749df72ec9b7730541bc'
> > tronWeb.trx.getConfirmedTransaction(transactionID).then(({raw_data_hex, signature}) => {
> >     console.log('raw_data_hex:', raw_data_hex)
> >     console.log('signature:', signature[0])
> >     const transactionByteLength = 9 + 60 + Buffer.from(raw_data_hex, 'hex').byteLength + Buffer.from(signature[0], 'hex').byteLength
> >     console.log('transaction byte length:', transactionByteLength)
> > })
> > ```
> 
> Could you explain where that fixed 69 bytes come from?

It's necessary to find out how protobuf works. I think this extra 69 bytes are protobuf header

**Comment by minseon9** [comment]
> > > @JessDotJS @matilareo Hello, I found the solution in JavaScript. If you check [proto file](https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto) you will see what Transaction consists of.
> > > ```proto
> > > message Transaction {
> > > 
> > >   // ...
> > > 
> > >   raw raw_data = 1;
> > >   // only support size = 1,  repeated list here for muti-sig extension
> > >   repeated bytes signature = 2;
> > >   repeated Result ret = 5;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So if we plus raw_data byte length, signature(s) byte length and extra fixed 69 bytes, we will get transaction byte length and bandwidth. I'm not sure if it's correct way, but I've checked some transactions and values were equal.
> > > Code works in Node.js. There isn't Buffer In browser, so it's necessary to use another way to get byte length
> > > ```js
> > > const tronWeb = new TronWeb({
> > >     fullHost: 'https://api.trongrid.io',
> > > })
> > > const transactionID = 'f23c438a1675cd0a93a8cd07145a97aad8b52e704b05749df72ec9b7730541bc'
> > > tronWeb.trx.getConfirmedTransaction(transactionID).then(({raw_data_hex, signature}) => {
> > >     console.log('raw_data_hex:', raw_data_hex)
> > >     console.log('signature:', signature[0])
> > >     const transactionByteLength = 9 + 60 + Buffer.from(raw_data_hex, 'hex').byteLength + Buffer.from(signature[0], 'hex').byteLength
> > >     console.log('transaction byte length:', transactionByteLength)
> > > })
> > > ```
> > 
> > 
> > Could you explain where that fixed 69 bytes come from?
> 
> It's necessary to find out how protobuf works. I think this extra 69 bytes are protobuf header

maybe I found out.

If you see the [code in java-tron](https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/java/org/tron/core/db/BandwidthProcessor.java#L91)
```
    if (chainBaseManager.getDynamicPropertiesStore().supportVM()) {
      bytesSize = trx.getInstance().toBuilder().clearRet().build().getSerializedSize();
    } else {
      bytesSize = trx.getSerializedSize();
    }

    for (Contract contract : contracts) {
      if (contract.getType() == ShieldedTransferContract) {
        continue;
      }
      if (chainBaseManager.getDynamicPropertiesStore().supportVM()) {
        bytesSize += Constant.MAX_RESULT_SIZE_IN_TX;
      }
   ...
```
transaction byteSize is calculated through serializing transaction without Ret field and adding the MAX_RESULT_SIZE_IN_TX which is 64.
Extra 5 bytes come from the protobuf LEN typed tag and len-prefix.
protobuf represents data as (tag)(len-prefix if needed)(data).
len-prefix is length of data and represented as Base 128 Varints. 
Briefly, len-prefix takes 1byte if data length is under 127 or takes 2bytes.
```
message Transaction {

  // ...

  raw raw_data = 1;
  // only support size = 1,  repeated list here for muti-sig extension
  repeated bytes signature = 2;
  repeated Result ret = 5;
}
```
raw_data and signature have LEN tag and need len-prefix.
So, two filed in transaction represented as (tag) (len-prefix) (data)
tag is one byte per filed and transaction without ret filed has two filed, raw_data and signature.
len-prefix of raw_data takes 2 bytes cause it is usually bigger than 127 byte and signature which is 65bytes(r,s,v) takes 1 bytes.

Finally we got 
```
const transactionByteLength = Buffer.from(raw_data_hex, 'hex').byteLength + Buffer.from(signature[0], 'hex').byteLength + 64 + 5
```
