### ISSUE TITLE
Bad code style, concatenates strings using + in a loop

### ISSUE THREAD

**Issue by bjianhang** [tronprotocol/wallet-cli#297]
Using "+" to concatenate strings is bad code style. This would cause performance issue. 

public static String printAccount(Account account) {
    String result = "";
    result += "address: ";
    result += WalletApi.encode58Check(account.getAddress().toByteArray());
    result += "\n";
    if (account.getAccountId() != null && !account.getAccountId().isEmpty()) {
      result += "account_id: ";
      result += new String(account.getAccountId().toByteArray(), Charset.forName("UTF-8"));
      result += "\n";
    }
    if (account.getAccountName() != null && !account.getAccountName().isEmpty()) {
      result += "account_name: ";
      result += new String(account.getAccountName().toByteArray(), Charset.forName("UTF-8"));
      result += "\n";
    }
    result += "type: ";
    result += account.getTypeValue();
    result += "\n";
    result += "balance: ";
    result += account.getBalance();
    result += "\n";
    if (account.getFrozenCount() > 0) {
      for (Frozen frozen : account.getFrozenList()) {
        result += "frozen";
        result += "\n";
        result += "{";
        result += "\n";
        result += "  frozen_balance: ";
        result += frozen.getFrozenBalance();
        result += "\n";
        result += "  expire_time: ";
        result += new Date(frozen.getExpireTime());
        result += "\n";
        result += "}";
        result += "\n";
      }
    }
    result += "free_net_usage: ";
    result += account.getFreeNetUsage();
    result += "\n";
    result += "net_usage: ";
    result += account.getNetUsage();
    result += "\n";
    if (account.getCreateTime() != 0) {
      result += "create_time: ";
      result += new Date(account.getCreateTime());
      result += "\n";
    }
    if (account.getVotesCount() > 0) {
      for (Vote vote : account.getVotesList()) {
        result += "votes";
        result += "\n";
        result += "{";
        result += "\n";
        result += "  vote_address: ";
        result += WalletApi.encode58Check(vote.getVoteAddress().toByteArray());
        result += "\n";
        result += "  vote_count: ";
        result += vote.getVoteCount();
        result += "\n";
        result += "}";
        result += "\n";
      }
    }
    if (account.getAssetCount() > 0) {
      for (String name : account.getAssetMap().keySet()) {
        result += "asset";
        result += "\n";
        result += "{";
        result += "\n";
        result += "  name: ";
        result += name;
        result += "\n";
        result += "  balance: ";
        result += account.getAssetMap().get(name);
        result += "\n";
        result += "  latest_asset_operation_time: ";
        result += account.getLatestAssetOperationTimeMap().get(name);
        result += "\n";
        result += "  free_asset_net_usage: ";
        result += account.getFreeAssetNetUsageMap().get(name);
        result += "\n";
        result += "}";
        result += "\n";
      }
    }
    result += "asset issued id:";
    result += account.getAssetIssuedID().toStringUtf8();
    result += "\n";
    if (account.getAssetV2Count() > 0) {
      for (String id : account.getAssetV2Map().keySet()) {
        result += "assetV2";
        result += "\n";
        result += "{";
        result += "\n";
        result += "  id: ";
        result += id;
        result += "\n";
        result += "  balance: ";
        result += account.getAssetV2Map().get(id);
        result += "\n";
        result += "  latest_asset_operation_timeV2: ";
        result += account.getLatestAssetOperationTimeV2Map().get(id);
        result += "\n";
        result += "  free_asset_net_usageV2: ";
        result += account.getFreeAssetNetUsageV2Map().get(id);
        result += "\n";
        result += "}";
        result += "\n";
      }
    }
    if (account.getFrozenSupplyCount() > 0) {
      for (Frozen frozen : account.getFrozenSupplyList()) {
        result += "frozen_supply";
        result += "\n";
        result += "{";
        result += "\n";
        result += "  amount: ";
        result += frozen.getFrozenBalance();
        result += "\n";
        result += "  expire_time: ";
        result += new Date(frozen.getExpireTime());
        result += "\n";
        result += "}";
        result += "\n";
      }
    }
    result += "latest_opration_time: ";
    result += new Date(account.getLatestOprationTime());
    result += "\n";

    result += "latest_consume_time: ";
    result += account.getLatestConsumeTime();
    result += "\n";

    result += "latest_consume_free_time: ";
    result += account.getLatestConsumeFreeTime();
    result += "\n";

    result += "allowance: ";
    result += account.getAllowance();
    result += "\n";

    result += "latest_withdraw_time: ";
    result += new Date(account.getLatestWithdrawTime());
    result += "\n";

//    result += "code: ";
//    result += account.getCode();
//    result += "\n";
//
    result += "is_witness: ";
    result += account.getIsWitness();
    result += "\n";
//
//    result += "is_committee: ";
//    result += account.getIsCommittee();
//    result += "\n";

    result += "asset_issued_name: ";
    result += account.getAssetIssuedName().toStringUtf8();
    result += "\n";
    result += "accountResource: {\n";
    result += printAccountResource(account.getAccountResource());
    result += "\n";
    result += "acquiredDelegatedFrozenBalanceForBandwidth: ";
    result += account.getAcquiredDelegatedFrozenBalanceForBandwidth();
    result += "\n";
    result += "delegatedFrozenBalanceForBandwidth: ";
    result += account.getDelegatedFrozenBalanceForBandwidth();
    result += "\n";
    result += "acquiredDelegatedFrozenBalanceForEnergy: ";
    result += account.getAccountResource().getAcquiredDelegatedFrozenBalanceForEnergy();
    result += "\n";
    result += "delegatedFrozenBalanceForEnergy: ";
    result += account.getAccountResource().getDelegatedFrozenBalanceForEnergy();
    result += "}\n";

    if (account.hasOwnerPermission()) {
      result += "owner_permission: ";
      result += "\n";
      result += "{";
      result += "\n";
      result += printPermission(account.getOwnerPermission());
      result += "\n";
      result += "}";
      result += "\n";
    }

    if (account.hasWitnessPermission()) {
      result += "witness_permission: ";
      result += "\n";
      result += "{";
      result += "\n";
      result += printPermission(account.getWitnessPermission());
      result += "\n";
      result += "}";
      result += "\n";
    }

    if (account.getActivePermissionCount() > 0) {
      result += "active_permissions: ";
      result += printPermissionList(account.getActivePermissionList());
    }

    return result;
  }

**Comment by zk19862018** [comment]
Thanks for your suggestion, will change the code.

**Comment by zk19862018** [comment]
Hi,

We have improved the code. Thanks again.
