### ISSUE TITLE
netty-common version conflicts

### ISSUE THREAD

**Issue by tensecond** [tronprotocol/wallet-cli#323]
1、spring-cloud-starter-consul-discovery dependence netty-common:4.0.27.Final
2、grpc-netty dependence netty-common:4.1.17.Final

wallet-cli no need spring-cloud-starter-consul-discovery,should be remove

**Comment by shydesky** [comment]
> 1、spring-cloud-starter-consul-discovery dependence netty-common:4.0.27.Final
> 2、grpc-netty dependence netty-common:4.1.17.Final
> 
> wallet-cli no need spring-cloud-starter-consul-discovery,should be remove

Is there any problem that occurs when the package conflict?

**Comment by 317787106** [comment]
@tensecond there is no conflict if spring-cloud-starter-consul-discovery and grpc-netty exist at the same time although they depends on two different version of netty-common. Error occurs if spring-cloud-starter-consul-discovery is missing, but it is ok when grpc-netty .

**Comment by 317787106** [comment]
@tensecond I package this wallet-cli project of branch develop into a wallet-cli.jar, and import it as an external jar into a new project. test it as this:

```
  public static void main(String[] args) throws Exception {
    List<String> fullnodes = new ArrayList<>();
    fullnodes.add("47.252.19.181:50051");
    List<String> soliditynodes = new ArrayList<>();
    GrpcClient grpcClient = new GrpcClient(fullnodes,soliditynodes);
  }
```

it works.

What has happened to you?

**Comment by shydesky** [comment]
hello, @tensecond We will close this issue because of no more response getting from you for a long time. Please feel free to reopen this issue if you have a question about this issue. Thank you!
