### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [tronprotocol/wallet-cli#353]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Benson0224** [comment]
same as https://github.com/tronprotocol/java-tron/issues/3087,  we will update this issue once we got progress.

**Comment by Benson0224** [comment]
Close this issue and let us use  https://github.com/tronprotocol/java-tron/issues/3087 to follow it. thanks.
