### ISSUE TITLE
How to tranplant wallet-cli to maven 

### ISSUE THREAD

**Issue by yujia77fxm** [tronprotocol/wallet-cli#357]
We got requirements to transplant wallet-cli from gradle to maven.but there are many problems for dependencies and project cannot be compiled .  please check the issue  thank you

**Comment by zhangwenhua-tron** [comment]
Can you provide some more details? What problems have you met?
If you want to use maven, you need to include all the dependencies in the gradle.

For example:
jline in maven:
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline</artifactId>
    <version>${jline.version}</version>
</dependency>

in gradle:
dependencies {
  compile group: 'org.jline', name: 'jline', version: '3.15.0'
}

**Comment by Benson0224** [comment]
thanks for your contribution.
We will close this issue since there is no update for a long time ago.
Please feel free to re-open it if you still have questions. thanks.
