### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by kerbyrok** [tronprotocol/wallet-cli#407]
I really didn't know who else to ask. I guess my wallet is stuck on some kind of smart contract. Everytime I deposit trx to it. Some how it's sent to another address before it can even completely clear the blockchain. Can anyone please help..

**Comment by alirezakm10** [comment]
leave the past scam smart contracts they codes can be work after scammed

**Comment by Benson0224** [comment]
Thanks for your contribution to wallet-cli, this issue will be closed since no update for a long time.
Please feel free to re-open it if you still see the issue in the latest version. thanks.
