### ISSUE TITLE
钱包默认trc20转账时的有效期较短，在网络环境不理想的情况下很容易出现交易不上链的情况

### ISSUE THREAD

**Issue by fbaiesec** [tronprotocol/wallet-cli#409]
通过代码，可以手动设置该有效期，不过建议可以将有效期设置为5分钟或者更长。
ps：我是用官方节点进行交易的查找和发送，经常出现官方节点区块同步落后于浏览器的情况，因此我将交易有效期设置的较大，来确保在发生落后情况下还能使得交易成功

**Comment by Benson0224** [comment]
Thanks for your contribution to wallet-cli. 

The expiration time is configured in the FULLNODE config file.  check detail here: https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L436

As you mentioned you can modify the expiration time before broadcast.  

Thanks for your sharing and we will close this issue now, please feel free to re-open it if you still see the issue, thanks.
