### ISSUE TITLE
api CreateTransaction  can not set expiration 

### ISSUE THREAD

**Issue by libangzhu** [tronprotocol/wallet-cli#414]
i can not set the tx's expiration when i create a the normal transaction.
from this doc: 
https://developers.tron.network/reference#walletcreatetransaction

by the way ,how to set a assign timestamp 
 
![image](https://user-images.githubusercontent.com/16385190/110908082-49dcf200-8349-11eb-8de5-cc7178957104.png)

**Comment by joe192** [comment]
Remove expiration

**Comment by vivian-kang** [comment]
/wallet/createtransaction is a java-tron fullnode http api.
1. for expiration, there is a configure item in fullnode config file: trx.expiration.timeInMilliseconds, it sets the number of milliseconds after the creation of the transaction that is expired, default value is  60000 ms. You can set it for your fullnode.
2. timestamp is the system current time in milliseconds set by fullnode

**Comment by Benson0224** [comment]
Thanks for your contribution to wallet-cli, this issue will be closed since no update for a long time.
Please feel free to re-open it if you still see the issue in the latest version. thanks.
