### ISSUE TITLE
GenerateAddress return failed!

### ISSUE THREAD

**Issue by MohseniBigBoy** [tronprotocol/wallet-cli#435]
when I run 
```
$ cd wallet-cli
$ ./gradlew build
$ cd build/libs
$ java -jar wallet-cli.jar
wallet> RegisterWallet
wallet> login
Login successful !!!
wallet> GetAddress 
GetAddress failed!
null
wallet> GenerateAddress 
GenerateAddress failed!
UNAVAILABLE: io exception
Connection refused: 127.0.0.1/127.0.0.1:50055
```

 /main/resources/config.conf contains:

> 
>  net {
>  #type = mainnet
>  type = testnet
> }
> 
> fullnode = {
>   ip.list = [
>     "127.0.0.1:50055"
>   ]
> }
> 
> #soliditynode = {
> #the IPs in this list can only be totally set to solidity or pBFT.
> #ip.list = [
> #"127.0.0.1:50052" // default solidity
> #]
> #ip.list = [
> #"127.0.0.1:50071" // or pBFT
> #]
> #}
> RPC_version = 2
> #This field used in shielded transaction. It is recommended that this field is set to the block
> #number in which the earliest relevant shielded contract was created. If the exact number is not
> #known, this field can be set as follows. If used in mainnet, please set 22690588. If used in Nile
> #testnet, please set 6380000. Otherwise, please set 0.
> blockNumberStartToScan = 6380000

**Comment by Benson0224** [comment]
from the wallet-cli config file, seems you are trying to connect a local full node, please confirm this first. 
if yes, Could you please share your full node configuration file? 

Pay attention to the RPC configuration part.  This is the example file for a private network.  please chek which port did you configured in the RPC section. the port in wallet-cli config should be the same as full node.
https://github.com/tronprotocol/tron-deployment/blob/master/private_net_config.conf#L123

**Comment by MohseniBigBoy** [comment]
Oh, I think using the wallet-cli I can run a Node! I want only GenerateAddress, Send, and GetTransaction if possible. I think I can do this using [tronpy](https://tronpy.readthedocs.io/en/latest/quickstart.html#installation)! but I don't know how to lunch a Tron node to interact by the tronpy. I try to build [java-tron](https://tronprotocol.github.io/documentation-en/developers/deployment/) but my software system is not enough! (my CPU core is 16 and RAM is 16GB).
How I can lunch a light full node to interact with tronpy?

**Comment by Benson0224** [comment]
Thanks for your info:
1. This is the guide of how to run a node: https://developers.tron.network/docs/fullnode
2.  Wallet-cli can connect to any testnet, no need to run a node if you just want to do some test, you cannect to shasta or nile test net.  here is the testnet info: https://developers.tron.network/docs/getting-started#5testnet 
3.  Tronpy can also interact with Shasta or nile test net. try it.

**Comment by MohseniBigBoy** [comment]
That's right, but how can I launch light full node?
My PC hardware is less than 1TB.

**Comment by Benson0224** [comment]
There is no issue at all, every time you call the `generate_address` function, it will generate a new address for you. 

From the source code, I can see that this function is an offline function, no connection is needed to run it. 
code: https://github.com/andelf/tronpy/blob/master/tronpy/async_tron.py#L538 

if you want to test the connection please try below function: 
` client.get_latest_block_number() 
`

**Comment by MohseniBigBoy** [comment]
Thanks, I can run a node at mainnet mode by [https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf), But I can not run in testnet mode by this [https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf) ! 
When I run `java -jar FullNode.jar -c config.conf` I get:
```
Exception in thread "main" java.lang.IllegalArgumentException: The address() must be 21 bytes.
	at org.tron.common.args.Account.setAddress(Account.java:53)
	at org.tron.core.config.args.Args.createAccount(Args.java:792)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.tron.core.config.args.Args.getAccountsFromConfig(Args.java:785)
	at org.tron.core.config.args.Args.setParam(Args.java:361)
	at org.tron.program.FullNode.main(FullNode.java:49)
```
How I can run the Node at testnet mode?

**Comment by Benson0224** [comment]
Running a private network requires at least one SR node,  please follow this guide to build your own private network: 
https://developers.tron.network/docs/tron-private-chain

**Comment by MohseniBigBoy** [comment]
Thanks very much. 🌹🙏
