### ISSUE TITLE
What is difference between wallet-cli and tronpy?

### ISSUE THREAD

**Issue by MohseniBigBoy** [tronprotocol/wallet-cli#437]
I run a Tron Full Node to generate new address, send(transfer) and get received by address transactions list (like bitcoin).  But I don't know what is difference between [tronpy](https://github.com/andelf/tronpy) and [wallet-cli](https://github.com/tronprotocol/wallet-cli)?

Can I do that works without launching a node?

**Comment by Benson0224** [comment]
TRON developer HUB is a good place to start with. 
https://developers.tron.network/docs/build-a-decentralized-library
