### ISSUE TITLE
Block production issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/wallet-cli#443]
Hi,
Running private node in tron. In 'supernode.conf' file, mentioned 27 SR's it will produces block successfully.
But creating one SR with highest voting other than 27 SR's. The created highest voting SR didn't create block, but the 'isJobs' status is 'true' and it results missed blocks.

**Comment by vivian-kang** [comment]
Hi, 
Is the node running on TRON mainnet or your private chain? 
If it is private chain, suggest to refer to this doc to double check the chain configuration. https://developers.tron.network/docs/tron-private-chain 

yes, if a node is a witness, then the 'isJobs' will be true, and after the node has already synchronized to the latest block, the node will generate block.

**Comment by osiz-blockchainapp** [comment]
> Hi,
> Is the node running on TRON mainnet or your private chain?
> If it is private chain, suggest to refer to this doc to double check the chain configuration. https://developers.tron.network/docs/tron-private-chain
> 
> yes, if a node is a witness, then the 'isJobs' will be true, and after the node has already synchronized to the latest block, the node will generate block.

Running private chain in tron. How to check the node is synchronized or not?

**Comment by vivian-kang** [comment]
For private chain, the genesis block will be generated by your witness node, so you should check the node's configuration according to the guide. if the witness node can not generate block, there must be something wrong of the configuration.

**Comment by osiz-blockchainapp** [comment]
> For private chain, the genesis block will be generated by your witness node, so you should check the node's configuration according to the guide. if the witness node can not generate block, there must be something wrong of the configuration.

Setup 27 SR's in genesis file.Again i created 1 SR with highest vote.
Does the highest vote SR mine blocks or not?

**Comment by Benson0224** [comment]
Please provide the log of the Super node and Fullnode for further invetigation. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.

This issue will be closed as no update for a long time. 

Please feel free to re-open it if you still see this issue, thanks.
