### ISSUE TITLE
Fail to execute command TriggerConstantContract

### ISSUE THREAD

**Issue by qing-wang** [tronprotocol/wallet-cli#446]
```
wallet> TriggerConstantContract TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t symbol() # false
symbol():95d89b41
RPC create call trx failed!
Code = CONTRACT_VALIDATE_ERROR
Message = contract validate error : No contract or not a smart contract

```

TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t is the contract address of TRC20. However, wallet-cli responses 'No contract or not a smart contract'.

**Comment by vivian-kang** [comment]
Please check the network which the wallet-cli is connect to. it should be Tron mainnet.

**Comment by qing-wang** [comment]
https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

The configuration I used for my own node is as the above. I think it connects to the mainnet.

**Comment by vivian-kang** [comment]
You should check the wallet-cli's configuration file: wallet-cli/src/main/resources/config.conf, check the ip.list in fullnode section. for example this is to connect to mainnet:
fullnode = {
  ip.list = [
    "grpc.trongrid.io:50051"
  ]
}

**Comment by qing-wang** [comment]
Yes, you are right. The fullnode I connected to is not connected to the mainnet.
