### ISSUE TITLE
How to specify config file for wallet.jar

### ISSUE THREAD

**Issue by bluedusk** [tronprotocol/wallet-cli#451]
Hi team, 

If I was to download wallet.jar and use it directly, how can I specify config file ?
Somethine like :

```
java -jar wallet.jar -config=myconfig.conf

```
Is it possible ?

Thanks.

**Comment by Benson0224** [comment]
make sure `wallet-cli.jar` and `config.conf` are in the same folder.  `wallet-cli.jar` will load it automatically.
