### ISSUE TITLE
http2 exception

### ISSUE THREAD

**Issue by Masoud-garazhian** [tronprotocol/wallet-cli#452]
HI 
I've installed and run the project. i could generate keys and etc. but when it comes to call the full node ( which i used online Apis)
ill get error by calling for example "GetBalance" command .
```
INTERNAL: http2 exception
First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```
and here is my config.conf file 
```
fullnode = {
  ip.list = [
    "api.trongrid.io"  
  ]
}
```

**Comment by Benson0224** [comment]
Wallet-cli is based on GRPC,  below are the GRPC info of trongrid. 
```
FullNode GRPC -
grpc.trongrid.io:50051

SolidityNode GRPC -
grpc.trongrid.io:50052
```

change the configuration as below and try again. 

![image](https://user-images.githubusercontent.com/61768920/131655292-0eb2e22b-7e0b-4113-9993-96777562cf71.png)
