### ISSUE TITLE
getTransactionInfoById中字段解析不正确

### ISSUE THREAD

**Issue by ian-gao** [tronprotocol/wallet-cli#470]
在合约中操作usdt转账, 交易详情会有log数据,   log中有address字段, 内容为usdt合约地址.
getTransactionInfoById 方法解析该log数据时,  address字段解析不正确.

**Comment by zhangwenhua-tron** [comment]
The log.address from the getTransactionInfoById is the base58 without T(0x41).

**Comment by Benson0224** [comment]
thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.
