### ISSUE TITLE
central.maven.org was not available in src/main/protos/install-googleapis.sh

### ISSUE THREAD

**Issue by sc0Vu** [tronprotocol/wallet-cli#487]
When I try to generate photo files, the script stopped because of central.maven.org not found error.

Script: https://github.com/tronprotocol/wallet-cli/blob/develop/src/main/protos/install-googleapis.sh

The script in java-torn worked: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/install-googleapis.sh

This worked too: wget https://repo.maven.apache.org/maven2/com/google/api/grpc/googleapis-common-protos/0.0.3/googleapis-common-protos-0.0.3.jar

**Comment by zhangwenhua-tron** [comment]
Thanks for your feedback, we will update the script.

**Comment by zhangwenhua-tron** [comment]
This issue has been fixed by https://github.com/tronprotocol/wallet-cli/pull/505.
