### ISSUE TITLE
Basic questions about the scope of wallet-cli project

### ISSUE THREAD

**Issue by aaa8212** [tronprotocol/wallet-cli#490]
Hi all,

I am trying to figure out if it would be possible to use wallet-cli as a service which would hold multiple private keys (protected with password) and allow making transactions with them.

I found it difficult to find the information about what this project supports in README (or elsewhere), so I would appreciate if someone could answer a few basic questions about the scope of wallet-cli:

1) does it support any sort of interface (json-rpc, gRPC, REST API,...) other than CLI?
2) does it allow saving private keys for more than a single account?

I did try running it, so I suspect the answer to both of the questions is "no" - but I would appreciate an official confirmation.

**Comment by zhangwenhua-tron** [comment]
Hi @aaa8212 ,

When you run wallet-cli, you can type `help` to get all the command it supports.

> 1. does it support any sort of interface (json-rpc, gRPC, REST API,...) other than CLI?

Actually, wallet-cli will send gRPC request to the fullnode according to your config(). 



> 2. does it allow saving private keys for more than a single account?

Yes, it allows you to save many accounts.
You can use ImportWallet to do this.

**Comment by BigBlueHundids** [comment]
> Hi all,
> 
> I am trying to figure out if it would be possible to use wallet-cli as a service which would hold multiple private keys (protected with password) and allow making transactions with them.
> 
> I found it difficult to find the information about what this project supports in README (or elsewhere), so I would appreciate if someone could answer a few basic questions about the scope of wallet-cli:
> 
> 1. does it support any sort of interface (json-rpc, gRPC, REST API,...) other than CLI?
> 2. does it allow saving private keys for more than a single account?
> 
> I did try running it, so I suspect the answer to both of the questions is "no" - but I would appreciate an official confirmation.

**Comment by Morris05** [comment]
https://github.com/tronprotocol/wallet-cli/issues/490#issuecomment-1200841319

**Comment by Morris05** [comment]
> Hi @aaa8212 ,
> 
> When you run wallet-cli, you can type `help` to get all the command it supports.
> 
> > 1. does it support any sort of interface (json-rpc, gRPC, REST API,...) other than CLI?
> 
> Actually, wallet-cli will send gRPC request to the fullnode according to your config().
> 
> > 2. does it allow saving private keys for more than a single account?
> 
> Yes, it allows you to save many accounts. You can use ImportWallet to do this.
