### ISSUE TITLE
Wallet-cli sendcoin faild！How should I deal with this problem？

### ISSUE THREAD

**Issue by axiang-huge** [tronprotocol/wallet-cli#530]
**The SendCoin command fails to be executed using wallet-cli. What can I do if the following information is displayed?**

**The failure information is as follows:**
```
sendcoin failed!
ec2a4f2049b9350382906f14a6e70bec4195085f10a812c1c3d8db9c0af154fb701b061fb7bf05c94e4d6a3fc6216f6b27ba88b704853e4396a1bf596ab6bc1d00 is signed by TCaF9bUQzZbBtHXFHcLHKi44g43ijFqdnz but it is not contained of permission.
```

**Comment by m-o-m12** [comment]
For account does not have permission, there are usually two possibilities: The first one is wrong account selection, that is the wrong privatekey used to sign the transaction, Please check whether the selected keystore file is consistent with the login account. The second is the account selected to sign the transaction does not have the permission to transfer TRX from the login account , and please check or modify the account permission.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
