### ISSUE TITLE
Get NullPointerException when call BroadcastTransaction API

### ISSUE THREAD

**Issue by magiczhao** [tronprotocol/wallet-cli#545]
Hi, I constructed a transaction to deploy a smart contract. And when I call the BroadcastTransaction API, I got the following error:

{"Error":"class java.lang.NullPointerException : null"}

Following is my steps to construct the request:

1. I call DeployContract API first to get the raw data, contract address and transaction id. this is successful.
2. I used JSON to encode the raw_data and calculated sha256 hash.
3. Sign the hash and get the signature.
4. Construct the signed transaction and call wallet/broadcasttransaction
Here is the transaction body :
[tron_request.txt](https://github.com/tronprotocol/wallet-cli/files/10596852/tron_request.txt)

Can anyone help me check what's wrong? Thanks!

**Comment by hzj-edu-nju** [comment]
To deploy a contract, you only need to call deploycontract

From your description, when the first step is executed, you have successfully deployed

Log just like
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/6916693/224936968-88f8eb1c-2b88-4a7c-b609-52b030b1f505.png">

**Comment by magiczhao** [comment]
Thanks, for your reply, but this contract can't be found from the explorer

**Comment by bladehan1** [comment]
You can refer to the example operation of deploying the contract in the readme

<img width="894" alt="image" src="https://user-images.githubusercontent.com/100394498/225559682-2c467845-81dd-47bc-96fe-8f546b28d298.png">

**Comment by ethan1844** [comment]
This issue will be closed as no update for a long time, please feel free to re-open it if you still see the issue, thanks.
