### ISSUE TITLE
Transaction sign error

### ISSUE THREAD

**Issue by liangxingnian** [tronprotocol/wallet-cli#550]
Transaction.toByteArray()
Cannot resolve method 'toByteArray()'

**Comment by ccingiz** [comment]
Cina

**Comment by ccingiz** [comment]
Cingiz

**Comment by bladehan1** [comment]
Did you fail to compile?
Use the latest release code
Read the readme and then compile

**Comment by vivian-kang** [comment]
Thanks for your contribution to wallet-cli, this issue will be closed as no update for a long time.

Please feel free to re-open it if it still exists, thanks.
