### ISSUE TITLE
Exchange 

### ISSUE THREAD

**Issue by Miraclezrus** [tronprotocol/wallet-cli#601]
Order info

Complete time: 5.03.2023, 00:18:07
Exchange rate: 1 USDT = 0.97769687 USDC
Transaction ID: 6403c2ecf766ab0019f90787

Input transaction info

Tx hash: 
Amount: 10000 USDT
Recieved time: 

Output transaction info

Tx hash: 
Recipient address: TBFvGea4X4BDC45RicWhkKWAcUhxAAzpWX
Amount: 9776.96867507 USDC

ChangeNOW: Limitless crypto exchange

**Comment by ccingiz** [comment]
Cina
