### ISSUE TITLE
Tron lock trust wallet

### ISSUE THREAD

**Issue by irvinkupper** [tronprotocol/wallet-cli#633]

**Comment by irvinkupper** [comment]
99 usdt locked in trust wallet can't find the key

**Comment by irvinkupper** [comment]
https://tronscan.org/#/address/TYASr5UV6HEcXatwdFQfmLVUqQQQMUxHLS![image](https://user-images.githubusercontent.com/119877605/227963420-7e0a1a52-7696-4bd9-8247-323b20318ac0.png)

**Comment by irvinkupper** [comment]
https://tronscan.org/#/address/TYASr5UV6HEcXatwdFQfmLVUqQQQMUxHLS![image](https://user-images.githubusercontent.com/119877605/227963420-7e0a1a52-7696-4bd9-8247-323b20318ac0.png)

**Comment by Jake151987** [comment]
@irvinkupper Would you mind providing the transaction hash?

**Comment by irvinkupper** [comment]
91d5a8b1bcae874036ffdfe![image](https://user-images.githubusercontent.com/119877605/229332672-279bfd6b-520d-4ac9-833e-e776004fb67b.png)

**Comment by Jake151987** [comment]
It seems the transaction is successfully made and the credit should be in your address. If you want to transfer or withdraw the 99 USDT and fail, you should check your address permission and see if you can find any unknown addresses listed. If so, you probably accidentally signed a transaction that changed your address permission weight. If that is not the case, you may ask TrustWallet customer service to see if there is something wrong with the client you are using. Either way, there is nothing we can do about it.
