### ISSUE TITLE
SM2 signature error

### ISSUE THREAD

**Issue by jingyukxy** [tronprotocol/wallet-cli#641]
we use sm2 signature transaction, but always return result as flow:
code : SIGERROR
message: "Validate signature error.xxxx"

**Comment by hitlxy** [comment]
Tron signature algorithm is ECDSA, curve used is SECP256K1.

**Comment by jingyukxy** [comment]
but we use the sm2 algorithm generate private key  in the client then signature use sm2 signature 
so is not tron network support sm2 signature yet?

**Comment by hitlxy** [comment]
Through SM2 is also supported by TRON, but now the configuration is to use ECDSA, so transactions are signed by SECP256K1 and all nodes use SECP256K1 to validate transactions, so if you use SM2 to generate privatekey and sign transactions, that will do not pass the validation.

**Comment by jingyukxy** [comment]
> Through SM2 is also supported by TRON, but now the configuration is to use ECDSA, so transactions are signed by SECP256K1 and all nodes use SECP256K1 to validate transactions, so if you use SM2 to generate privatekey and sign transactions, that will do not pass the validation.

if I deploy a node configure with crypto.engine as sm2 algorithm to verify signature , does it work?

**Comment by jingyukxy** [comment]
okay , now I generate  a address as sm2 algorithm and I had transfer some usdt to the wallet, how can i transfer out to another wallet?

**Comment by hitlxy** [comment]
Only the account's privatekey which generated using ECDSA can sign the transferring transaction.
