### ISSUE TITLE
Xd

### ISSUE THREAD

**Issue by Scheusal13** [tronprotocol/wallet-cli#660]

**Comment by Jake151987** [comment]
@Scheusal13 Would you mind specifying the problem you met?

**Comment by samirbani** [comment]
> _لم يتم تقديم وصف._

https://github.com/tronprotocol/wallet-cli/issues/660#issuecomment-1620934157

**Comment by Jake151987** [comment]
Hi @samirbani, please let us know if you have any questions regarding wallet-cli.
