### ISSUE TITLE
Add resource price and memo fee query interfaces for wallet-cli

### ISSUE THREAD

**Issue by lxcmyf** [tronprotocol/wallet-cli#666]
# Rationale
In Java tron, there are already interfaces for resource unit price query`/wallet/getbandwidthprices` and`/wallet/getenergyprices`, as well as querying memo fee`/wallet/getmemofee`. These interfaces support HTTP and gRPC calls, but not wallet-cli. There, it is to add these APIs to **wallet-cli** so that make it convenient for developers to use.

# Implementation
Due to the fact that wallet cli, as a client, interacts with TRON service through gRPC, simply add gRPC calls to `/wallet/getbandwidthprices`,`/wallet/getenergyprices` and `/wallet/getmemofee`.

**Comment by halibobo1205** [comment]
LGTM
