### ISSUE TITLE
when start wallet-cli.jar, Using any of the three base commands doesn't work?

### ISSUE THREAD

**Issue by 405560984** [tronprotocol/wallet-cli#680]
use the master version. and make the jar successfully.
start the jar by command: java -jar wallet-cli.jar is successfully too.
and the question is when i input the three command(login registerwallet importwallet), It skips the password input stage and ends directly, and the tips like this :
wallet> registerwallet
registerwallet
Please input password.
password:
use user defined config file in current dir
walletapi getRpcVserion:2
registerwallet failed!
password is empty

why????

**Comment by Katarzynamm** [comment]
TAK Pilnujcie ZE NAWET Systemowe Miałem Odinstalowane!!!

K.Sz

czw., 2 lis 2023, 04:26 użytkownik 405560984 ***@***.***>
napisał:

**Comment by laurenceja** [comment]
@405560984 Password should not be empty. After input the "registerwallet" command, it prompts for setting a password.

**Comment by 405560984** [comment]
> @405560984 Password should not be empty. After input the "registerwallet" command, it prompts for setting a password.

Yes, the correct process is like this, but here it's directly skipped entering the password and then end. it will prompted that the password is empty. I don’t quite understand why this problem occurs.

**Comment by laurenceja** [comment]
@405560984 I tried it here and the function is normal. I am not sure if you typed "Enter".

**Comment by 405560984** [comment]
> @405560984 I tried it here and the function is normal. I am not sure if you typed "Enter".

in line wallet>
i input command "registerwallet" and then i click "Enter"! this is must be no problem.
but, it will skip all input message and end!
by the way, i use the command line in **GitBash window**, maybe it can not work in this system?
but when i get into window's CMD, it can't work!
eh, Could it be that the platform I chose to run the command line is wrong?

**Comment by lurais** [comment]
> > @405560984 I tried it here and the function is normal. I am not sure if you typed "Enter".
> 
> in line wallet> i input command "registerwallet" and then i click "Enter"! this is must be no problem. but, it will skip all input message and end! by the way, i use the command line in **GitBash window**, maybe it can not work in this system? but when i get into window's CMD, it can't work! eh, Could it be that the platform I chose to run the command line is wrong?

As I know, the wallet-cli has not been tested on windows, so it is not recommended to use it on windows. Have you tried to use it in other kind of systems?

**Comment by 405560984** [comment]
> > > @405560984 I tried it here and the function is normal. I am not sure if you typed "Enter".
> > 
> > 
> > in line wallet> i input command "registerwallet" and then i click "Enter"! this is must be no problem. but, it will skip all input message and end! by the way, i use the command line in **GitBash window**, maybe it can not work in this system? but when i get into window's CMD, it can't work! eh, Could it be that the platform I chose to run the command line is wrong?
> 
> As I know, the wallet-cli has not been tested on windows, so it is not recommended to use it on windows. Have you tried to use it in other kind of systems?

OK, i will try it in Linux Operation System! thanks...
