### ISSUE TITLE
Don't build ("Could not determine java version from '21'.")

### ISSUE THREAD

**Issue by safocl** [tronprotocol/wallet-cli#682]
I cloned repo, then `./gradlew build` and get an error 
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '21'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Archlinux OS with:
```
╰─>$ gradle --version

------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-22 23:35:34 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21 (Oracle Corporation 21+35)
OS:           Linux 6.5.9-arch2-1 amd64
```

```
╰─>$ java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
```

**Comment by CarlChaoCarl** [comment]
@safocl 

I use java version "1.8" and there is no problem compiling wallet-cli.
You should use java8 instead of java21, try again.
If you need any more help, please join the Telegram：https://t.me/troncoredevscommunity

**Comment by Akugb** [comment]
tronWeb.createAccount()
> address:
{
    base58: "TDpBe64DqirkKWj6HWuR1pWgmnhw2wDacE"
    hex: "412A2B9F7641D0750C1E822D0E49EF765C8106524B"
    privateKey: "427139B43028A492E2705BCC9C64172392B8DB59F3BA1AEDAE41C88924960091"
    publicKey:"0404B604296010A55D40000B798EE8454ECCC1F8900E70B1ADF47C9887625D8BAE3866351A6FA0B5370623268410D33D345F63344121455849C9C28F9389ED9731"
}

**Comment by tadhaQ-nerfed-5misbu** [comment]
I need help moving wallet to exodus it belongs to me Christina

**Comment by 317787106** [comment]
This issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
