### ISSUE TITLE
Sing wallet 

### ISSUE THREAD

**Issue by Hsankhali** [tronprotocol/wallet-cli#693]
Updateaccountpermission TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ \ { "owner_permission": { "type": 0, "permission_name": "owner", "threshold": 1, "keys": [ { "address": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ", "weight": 1 } ] }, "witness_permission": { "type": 1, "permission_name": "owner", "threshold": 1, "keys": [ { "address": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ", "weight": 1 } ] }, "active_permissions": [ { "type": 2, "permission_name": "active12323", "threshold": 2, "operations": "7fff1fc0033e0000000000000000000000000000000000000000000000000000", "keys": [ { "address": "TNhXo1GbRNCuorvYu5JFWN3m2NYr9QQpVR", "weight": 1 }, { "address": "TKwhcDup8L2PH5r6hxp5CQvQzZqJLmKvZP", "weight": 1 } ] } ] }

**Comment by ccingiz** [comment]
> Hesabın yenilənməsi icazəsi TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ \ { "sahibi_icazə": { "növ": 0, "icazə_adı": "sahibi", "ərəfəsində": 1, "açarlar": [ { "ünvan": "TRGhNNfnmgLegTweet": "TRGhNNfnmgLegT4"v" ] }, "şahid_icazə": { "növ": 1, "icazə_adı": "sahibi", "ərəfəsində": 1, "açarlar": [ { "ünvan": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ", "çəki": 1 } ] }, "aktiv_icazələr": [ { "növ": 2, "icazə_adı": "aktiv12323", "həddi": 2, "əməliyyatlar": "7fff1fc0033e0000000000000000000000000000000000000000000000000000" ünvan": "TNhXo1GbRNCuorvYu5JFWN3m2NYr9QQpVR", "çəki ": 1 }, { "ünvan": "TKwhcDup8L2PH5r6hxp5CQvQzZqJLmKvZP", "çəki": 1 } ] } ] }

**Comment by ccingiz** [comment]
> Updateaccountpermission TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ \ { "owner_permission": { "type": 0, "permission_name": "owner", "threshold": 1, "keys": [ { "address": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ", "weight": 1 } ] }, "witness_permission": { "type": 1, "permission_name": "owner", "threshold": 1, "keys": [ { "address": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ", "weight": 1 } ] }, "active_permissions": [ { "type": 2, "permission_name": "active12323", "threshold": 2, "operations": "7fff1fc0033e0000000000000000000000000000000000000000000000000000", "keys": [ { "address": "TNhXo1GbRNCuorvYu5JFWN3m2NYr9QQpVR", "weight": 1 }, { "address": "TKwhcDup8L2PH5r6hxp5CQvQzZqJLmKvZP", "weight": 1 } ] } ] }
