### ISSUE TITLE
Block and unable to withdraw 

### ISSUE THREAD

**Issue by Frank9007** [tronprotocol/wallet-cli#723]
My USTD was unable to withdraw why

**Comment by lxcmyf** [comment]
@Frank9007 
Please provide a detailed description of the problems and operational steps you have encountered, including what network you are on, what clients you are using, what APIs you are using, and so on.

**Comment by 317787106** [comment]
@Frank9007 This issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
