### ISSUE TITLE
Cannot figure out AssetIssue command syntax

### ISSUE THREAD

**Issue by newskysecurity** [tronprotocol/wallet-cli#87]
I was successful when building and running server and wallet-cli, creating a local account and login, then I tried to execute AssetIssue on local node, with command copied from Readme.md:

assetIssue 88888888 testAssetIssue00001 10000000000000000 1 100 2018-4-1 2018-4-30 1 just-test https://github.com/tronprotocol/wallet-cli/

replaced 88888888 with my local account, however I got this error message:

Use assetIssue command you need like: 
AssetIssue AssetName TotalSupply TrxNum AssetNum StartDate EndDate Description Url FreeNetLimitPerAccount PublicFreeNetLimitFrozenAmount0 FrozenDays0 ... FrozenAmountN FrozenDaysN
TrxNum and AssetNum represents the conversion ratio of the tron to the asset.
The StartDate and EndDate format should look like 2018-3-1 2018-3-21 .

**Comment by Jacob8765** [comment]
I tried a while back and had the same issue.

**Comment by zk19862018** [comment]
AssetIssue TestTRX 100000 1 1 2 "2019-04-04 11:48:00" "2019-04-05" "just for test" www.test.com 
100 100000 10000 10 10000 1     
View published information:    
GetAssetIssueByAccount TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ     
11:50:02.688 INFO  [main] [Client](Client.java: 361)     
assetIssue 0 :::   
[   
Id: 1000001   
Owner_address: TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ   
Name: TestTRX   
Order: 0   
Total_supply: 100000   
Trx_num: 1   
Num: 1   
Precision 2   
Start_time: Thu Apr 04 11:48:00 CST 2019   
End_time: Fri Apr 05 00:00:00 CST 2019   
Vote_score: 0   
Description: just for test   
Url: www.test.com   
Free asset net limit: 100   
Public free asset net limit: 100000   
Public free asset net usage: 0   
Public latest free net time: 0   
Frozen_supply   
{   
  Amount: 10000   
  Frozen_days: 1    
}   
Frozen_supply    
{   
  Amount: 10000    
  Frozen_days: 10    
}   
]
