### ISSUE TITLE
Could not run web wallet. Error: no main manifest attribute, in wallet-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by mak2014** [tronprotocol/wallet-cli#88]
**What did you do?**

Trying to build and run web wallet using the below instructions

```
cd wallet-cli
./gradlew build       
cd build cd libs
java -jar wallet-1.0-SNAPSHOT.jar
```

**What did you expect to see?**

Run web wallet 

**What did you see instead?**

Error:  no main manifest attribute, in wallet-1.0-SNAPSHOT.jar

I have unzipped the jar file and noticed Manimest.MF file with this line only: 

Manifest-Version: 1.0

**Comment by renchenchang** [comment]
java -jar wallet-cli.jar

**Comment by mak2014** [comment]
@renchenchang I have followed the documentation here: https://github.com/tronprotocol/wallet-cli#build-and-run-web-wallet
Is it incorrect?

**Comment by kookiekrak** [comment]
@mak2014 I'll update the documentation, but running the other jar file should initialize the cli wallet
