### ISSUE TITLE
[Bounty] [wallet-cli] help Command - missing description of the commands 

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#94]
Bug Report
-----------
if i enter the help command -> I was expecting to receive a brief description of the commands.
![image](https://user-images.githubusercontent.com/39301026/41020085-d5d58bbe-6961-11e8-827d-b50dbdd81bb4.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
06. June 2018 8:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by kookiekrak** [comment]
Hi,

The documentation for the wallet  can be found here:

https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Protocol/TRON_Wallet_RPC-API.md

I'll work on surfacing the documentation better and fixing the links

**Comment by dbriggsie** [comment]
@PMD3VSolution I'm Currently working on updating Help Command List & better Definitions...
