### ISSUE TITLE
[Bounty] [wallet-cli] create wallet - password with a space cannot be set

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#97]
Bug Report
------------
password with a space cannot be set

Command: RegisterWallet
password:q w e r t z u i o p ü a s d f g h j k l ö ä y x c v b n m
![image](https://user-images.githubusercontent.com/39301026/41021282-2989e9fe-6966-11e8-88ab-e4801589466e.png)

result:
![image](https://user-images.githubusercontent.com/39301026/41021351-5ec2ad9a-6966-11e8-8d8e-2e3d8afd2fa6.png)

when i use the same password on tronscan.org it works:
![image](https://user-images.githubusercontent.com/39301026/41021419-a7b4a2f6-6966-11e8-8bb6-cb38a939658e.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
06. June 2018 8:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by kookiekrak** [comment]
@PMD3VSolution, thanks for reporting this!

This is an issue in Tronscan, located here: https://github.com/tronscan/tronscan-frontend

We've communicated this report to the maintainer of Tronscan so that they can fix it.

Keep up the good work!
