### ISSUE TITLE
[Bounty] [wallet-cli] create wallet - password verification faulty

### ISSUE THREAD

**Issue by PMD3VSolution** [tronprotocol/wallet-cli#98]
Bug Report
----------
the password complexity verification behaves differently on the wallet-cli and tronscan 

i try to create an wallet, command: RegisterWallet
![image](https://user-images.githubusercontent.com/39301026/41021774-ebae263e-6967-11e8-84df-ae6da255f293.png)

i enter this password:
>><<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>><<<<<<<<||||||||||||||||||||||<
![image](https://user-images.githubusercontent.com/39301026/41021965-804bba68-6968-11e8-9b39-b5a30de69576.png)

result:
![image](https://user-images.githubusercontent.com/39301026/41022029-a3096c30-6968-11e8-9aba-f358231ea012.png)

on tronscan , it works:
![image](https://user-images.githubusercontent.com/39301026/41022082-c3d2b93a-6968-11e8-99e2-4dd5757cc002.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
06. June 2018 8:00 am (UTC+1)

Tested OS
---------
centos
ubuntu

Bounty Program
--
https://twitter.com/justinsuntron/status/1002072890349531137

**Comment by Jacob8765** [comment]
I think Tronscan uses a separate algorithm for finding password strength.

**Comment by kookiekrak** [comment]
@PMD3VSolution, thanks for reporting this! 

This is an issue in Tronscan, located here: https://github.com/tronscan/tronscan-frontend

We've communicated this report to the maintainer of Tronscan so that they can fix it.

Keep up the good work!
