### ISSUE TITLE
How to deploy solidity smart contract ?

### ISSUE THREAD

**Issue by arunsybex** [tronprotocol/wallet-cli#99]
Hi I tried with this " deploy contract(password, contract address, abi, code, data, value)  ". But I can't deploy please give ideas

**Comment by zergweak** [comment]
We will support smart contracts in the future

**Comment by balajivs96** [comment]
okay. what we can do now with tron?

**Comment by zk19862018** [comment]
https://tronprotocol.github.io/documentation-EN/contracts/compiler/
